apiVersion: apps/v1
kind: Deployment
metadata:
  name: cineverse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nirmalrv8/cineverse-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
